### ISSUE TITLE
Key file to unlock

### ISSUE THREAD

**Issue by vingman** [leaty/rkeep#2]
Hello, I use both a keyfile and a password to unlock the database, but i don't see any option for this in the config file. Is this something you would consider adding?

**Comment by leaty** [comment]
Let me know if it works for you, I want to make a few more changes before next release so you'll have to pull from master.

**Comment by vingman** [comment]
Works for me! Thanks! 

One other thing that may be helpful in the future is having a way to open the password entry and select which field to copy to the clipboard (sometimes I have stuff stored in the 'notes' section or some other field that I need to copy and paste). At the very least, I need to be able to see which username/email I have associated with the keepass entry. Maybe this is already possible but I haven't yet stumbled on the correct key combo...

**Comment by leaty** [comment]
Great! :smile: 

No this is currently not possible in rkeep, but it is certainly plausible. Please make detailed issues out of of your suggestions, it helps a lot, this issue is closed so it's easily forgettable. However both of your suggestions sound like good features, albeit with the lack of detail I'm not sure how best to implement this. Perhaps you'd like to try implementing these yourself? Rust is awesome, so why not.
